// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package qrs

import ()

type Account struct {
	AccountNumber int32   `json:"accountNumber"`
	AccountState  bool    `json:"accountState"`
	Balance       float64 `json:"balance"`
	ClientName    string  `json:"clientName"`
}
